El CSS carga los logos oficiales y el JS marca correctamente la opcion
PyAr/wiki pull request #131
Opened 2021-05-09 04:41 UTC by tzulberti

El CSS estaba usando las imagenes locales y no las que estan en python.org.ar. No habia mucho problema con eso salvo que si quiero volver a usar el theme tengo errores.

El JS no estaba seleccionando la opcion correspondiente cuando se esta en produccion

2021-06-14 23:50 UTC, marcorichetta commented
Está bien qué la misma página tenga 2 urls diferentes?
En ese caso dejo una corrección para que el funcione con ambos `pathname`

### Lista de correo :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/19599150/121972600-dab0d880-cd51-11eb-8b86-f9f4282c5c09.png)

### Foro y redes :x:
![image](https://user-images.githubusercontent.com/19599150/121972620-e7cdc780-cd51-11eb-922e-01490f4ec285.png)

2021-06-14 23:53 UTC, marcorichetta requested changes
Agregué check para `pathname` "foro_y_redes"

![image](https://user-images.githubusercontent.com/19599150/121972851-6cb8e100-cd52-11eb-999e-01b76fcb7ab8.png)

2021-06-14 23:53 UTC, marcorichetta commented on themes/pyar/assets/js/pyar.js
> +} else if (pathname == "/listadecorreo/") {
```suggestion
} else if (pathname == "/listadecorreo/" || pathname == "/foro_y_redes/") {
```

2021-07-12 12:02 UTC, facundobatista commented
@marcorichetta esto ya estaría corregido, entonces? gracias!

2021-07-12 12:52 UTC, marcorichetta commented
> @marcorichetta esto ya estaría corregido, entonces? gracias!

Entiendo que sí. Mi sugerencia ya fue aplicada y lo demás ya estaba corregido.

2021-07-24 01:03 UTC, merged