La wiki se actualiza cuando se actualiza el repo de Wiki
PyAr/wiki pull request #134
Opened 2021-11-12 13:01 UTC by tzulberti

**Contexto**

La idea es actualizar la wiki que esta corriendo cada vez que se actualiza el repo. Para eso lo que hice es:
- hacer una webapp en Flask que se encarga de hacer un `git pull && nikola build` 
- cambiar la imagen de docker para que:
  - tenga los endpoints de Flask
  - corra Flask
  - los archivos estaticos de Nikola los siga sirviendo Nginx
- se configuro Sentry para la wiki
- Configurar github para que cada cosa que se cambie en el repo, mande un webhook a la app

Esto funciona, pero hay variaslimitaciones:
#. hay un caching del lado de Nginx o en algun lado que no pude encontrar donde esta que hace que se tarde en actualizar la pagina
#. No es el codigo mas lindo pero funciona. 
#. El webhook de Github siempre tira timeout. Eso es porque la app "tarda" mas de un par de segundos en actualizar todo

2021-11-22 13:39 UTC, facundobatista requested changes
Ahí anoté algunos detalles...

Me parece bien toda la idea. Con respecto a las limitaciones...

#. hay un caching del lado de Nginx o en algun lado que no pude encontrar donde esta que hace que se tarde en actualizar la pagina

¿Cuánto tarda? Con "saber" cuanto tarda, al principio, creo que estamos bien. O sea, "esperás cinco minutos y listo" está lo suficientemente bien...

#. No es el codigo mas lindo pero funciona.

:)

#. El webhook de Github siempre tira timeout. Eso es porque la app "tarda" mas de un par de segundos en actualizar tod

Arranquemos con esto, después vemos si ejecutamos "lo pesado" en un hilo o algo.


¡¡MUCHAS GRACIAS!!

2021-11-22 13:39 UTC, facundobatista commented on app/main.py
> +	force_build = False
te quedó mal indentado acá...

2021-11-22 13:39 UTC, facundobatista commented on app/main.py
> +def update():
metele docstrings a las funciones así es más fácil entender qué hacen

2021-11-22 13:39 UTC, facundobatista commented on app/main.py
> +		print("%s not found. Clonning repo" % CLONE_PATH)
Estos "print" dónde aparecen? 

Ya que estamos, usá .format o f-strings...

2021-11-22 13:39 UTC, facundobatista commented on app/main.py
> +	shutil.copytree(os.path.join(CLONE_PATH, 'output'), DESTINATION_PATH, dirs_exist_ok=True)
Acá lo ideal sería, en vez de "copiar todo a lo bruto", hacer un `rsync` para que "meta lo que cambió solamente"...

El comando sería algo como lo siguiente:
```
        cmd = ['rsync', '-t', '-r', '--delete', '--inplace', DIR_FUENTE, DIR_DESTINO]
```

2021-11-22 13:39 UTC, facundobatista commented on app/main.py
> +def git_checkout():
Es raro que esto que es "git checkout" NO HAGA "git checkout"

2021-11-22 14:02 UTC, tzulberti commented on app/main.py
> +def git_checkout():
es un endpoint de debug para saber la version de git. Voy a cambiar el nombre

2021-11-22 14:03 UTC, tzulberti commented on app/main.py
> +		print("%s not found. Clonning repo" % CLONE_PATH)
En los logs de Kubernetes. Me olvide de cambiarlo por logging

2021-11-22 14:03 UTC, tzulberti commented on app/main.py
> +	shutil.copytree(os.path.join(CLONE_PATH, 'output'), DESTINATION_PATH, dirs_exist_ok=True)
> Ahí anoté algunos detalles...
> 
> Me parece bien toda la idea. Con respecto a las limitaciones...
> 
> #. hay un caching del lado de Nginx o en algun lado que no pude encontrar donde esta que hace que se tarde en actualizar la pagina
> 
> ¿Cuánto tarda? Con "saber" cuanto tarda, al principio, creo que estamos bien. O sea, "esperás cinco minutos y listo" está lo suficientemente bien...

una hora. No pude encontrar donde esta eso configurado

2021-11-26 16:32 UTC, tzulberti commented
> #. hay un caching del lado de Nginx o en algun lado que no pude encontrar donde esta que hace que se tarde en actualizar la pagina
> 
> ¿Cuánto tarda? Con "saber" cuanto tarda, al principio, creo que estamos bien. O sea, "esperás cinco minutos y listo" está lo suficientemente bien...

El caching tarda mas o menos 30minutos. No pude encontrar de donde viene

> 
> #. No es el codigo mas lindo pero funciona.
> 
> :)

El codigo sigue siendo feo pero al menos ahora tenemos logging. 

> 
> #. El webhook de Github siempre tira timeout. Eso es porque la app "tarda" mas de un par de segundos en actualizar tod
> 
> Arranquemos con esto, después vemos si ejecutamos "lo pesado" en un hilo o algo.
> 

En el ultimo commit hice el tema de pasarlo a un thread. Ahora no tenemos mas errores en el webook de github con respecto a este tema

> ¡¡MUCHAS GRACIAS!!

De nada


Acabo deployar los ultimos cambios en staging y parecen estar funcionando

2021-11-27 19:30 UTC, merged